Using Bootstrap
BigWizzo/newsweek-clone pull request #1
Opened 2020-09-21 22:37 UTC by BigWizzo

# HTML and CSS: Using Bootstrap

*  This project clones the Newsweek Magazine website using the Bootstrap  Framework.

* The goal was to use Bootstrap CSS classes wherever it is possible.

2020-09-21 23:04 UTC, kevincappuccino requested changes
# [STATUS] CHANGES REQUIRED♻️

  
#### Hey team, Is a pleasure to review such a good project! Congrats for the amazing work you guys already did, the project looks really nice and I can see that you guys are working hard on it, and we're almost done, there are just some minor changes that you guys have to implement to proceed:

## [REQUIRED CHANGES]
#### Clone REQUIREMENTS 👥 (Those adjusts to make your page really look like the real one)⤵
- [x] All screens (Large, Medium, and Small) should have a fixed navbar.
- [x] That image is too shrieked, please fix that.
- Yours
![image](https://user-images.githubusercontent.com/56762529/93829447-0cbe5f80-fc44-11ea-8171-e9e385fb6cb8.png)
- Original
![image](https://user-images.githubusercontent.com/56762529/93829408-f1ebeb00-fc43-11ea-8a0a-5159d7b4deed.png)

- [x] These side images are too small, please take care of it! (Medium and Small screens)
- Yours
![image](https://user-images.githubusercontent.com/56762529/93829495-1fd12f80-fc44-11ea-8e70-31295154719b.png)
- Original
![image](https://user-images.githubusercontent.com/56762529/93829546-3bd4d100-fc44-11ea-9d9f-f88a2c55f6fe.png)

- [x] In small screens your subscribe section looks broken, please take care of it. ⤵
![image](https://user-images.githubusercontent.com/56762529/93829678-89e9d480-fc44-11ea-825a-496118fa3807.png)

#### Good practices REQUIREMENTS (Those changes to make you code like a pro 👽)⤵
- [ ] Kindly remember to remove all the unnecessarily repeated CSS code. Keeping your code DRY is an excellent practice that will help you a lot and make your code more professional. (Check this link form better understanding [Good and Bad CSS Practices for Beginners](https://speckyboy.com/good-bad-css-practices/)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright)
Take a look at this example:
![image](https://user-images.githubusercontent.com/56762529/90803794-a914df80-e2ef-11ea-9be0-40267c665254.png)
Your HTML will be something like this: 
![image](https://user-images.githubusercontent.com/56762529/90803950-e7120380-e2ef-11ea-8221-5d5d3a13e033.png)
Apply the same logic above in **ALL** these repeated rules listed below:
      18 |   font-weight: bold;
       6 |   color: white;

- [x] Please delete **commented piece of codes** in your HTML and CSS files. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))  
:x: **commented piece of codes** /* `.nav { color: red;}` */  
:heavy_check_mark: **comments about code** /*Navigation */  


## Please make the required changes and resubmit for a new code review once you are ready💪

## As always, I wish you all the very best and see you both at the top🚀

  👨🏻‍💻 **TSE: Kevin Alves**

    

  📫 Have any question? Better call Kevin:

  <a  href="mailto:kevinalves.js@gmail.com"> <img  alt="gmail"  src="https://img.shields.io/badge/gmail-%20- green?logo=gmail&style=social"></a> [![Twitter Follow](https://img.shields.io/twitter/follow/kevinnnmn?style=social)](https://twitter.com/intent/follow?screen_name=kevinnnmn) [![](https://img.shields.io/badge/Slack-Kevin%20Alves-green?logo=slack&style=social)](https://microverse-students.slack.com/team/UT86D3AP4)

    
  <sub>*We're here to help you, to ensure that you're using the best practices and getting you ready for the job market. In real-world, you'll have a lot of changes requests for your real clients, it's good to get used to it.</sub>

2020-09-21 23:04 UTC, kevincappuccino commented on index.html
> +  <!--  -->
- [ ] Please delete **commented piece of codes** in your HTML and CSS files. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))  
:x: **commented piece of codes** /* `.nav { color: red;}` */  
:heavy_check_mark: **comments about code** /*Navigation */

2020-09-21 23:04 UTC, kevincappuccino commented on index.html
> +      <!-- </div> -->
- [ ] Please delete **commented piece of codes** in your HTML and CSS files. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))  
:x: **commented piece of codes** /* `.nav { color: red;}` */  
:heavy_check_mark: **comments about code** /*Navigation */

2020-09-21 23:04 UTC, kevincappuccino commented on index.html
> +      <!-- </div> -->
- [ ] Please delete **commented piece of codes** in your HTML and CSS files. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))  
:x: **commented piece of codes** /* `.nav { color: red;}` */  
:heavy_check_mark: **comments about code** /*Navigation */

2020-09-21 23:04 UTC, kevincappuccino commented on index.html
> +      <!-- <div class="row"> -->
- [ ] Please delete **commented piece of codes** in your HTML and CSS files. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))  
:x: **commented piece of codes** /* `.nav { color: red;}` */  
:heavy_check_mark: **comments about code** /*Navigation */

2020-09-22 17:09 UTC, jubaan requested changes
# Status: Changes Required :recycle:

## :wave::wave::wave: Great work team!

Things to notice:

:100: Using for most part semantic HTML. See observations
:100: descriptive pull request and commit messages
:100: The website is starting to look awesome.
:100: Project has main sections

You've worked on most of the previous required changes, there are still some the project could improve.

- [x]  Links to social network Broken
![image](https://user-images.githubusercontent.com/25774518/93911609-3b7e1980-fcc8-11ea-9849-de89903f46d3.png)

- [x]  Issues and license links broken in README
![image](https://user-images.githubusercontent.com/25774518/93911691-5486ca80-fcc8-11ea-8a1a-35f1c09f0cfa.png)

- [x] navbar is missing menu and search input
![image](https://user-images.githubusercontent.com/25774518/93912143-f4dcef00-fcc8-11ea-8ccf-17b6f7f43c62.png)

- [x] navbar doesn't match original height
![image](https://user-images.githubusercontent.com/25774518/93913008-1b4f5a00-fcca-11ea-9c58-3d72496abc08.png)

- [x] overlaping section titles in most of the views
![image](https://user-images.githubusercontent.com/25774518/93913008-1b4f5a00-fcca-11ea-9c58-3d72496abc08.png)
![image](https://user-images.githubusercontent.com/25774518/93914605-62d6e580-fccc-11ea-9aa3-3625a5c944e7.png)
![image](https://user-images.githubusercontent.com/25774518/93912289-2e155f00-fcc9-11ea-9716-fcaef0c52c6e.png)

- [x] Subscribe section not displaying correctly
![image](https://user-images.githubusercontent.com/25774518/93912434-661ca200-fcc9-11ea-9642-a2c9a98bb0b2.png)

- [x] Navbar should be wrapper around ```header``` HTML tag.

## Keep the great work :muscle:, and Happy Coding :smiley: :computer:!

2020-09-22 20:39 UTC, blackpintz requested changes
# Status: Changes Required

### Hello team,

**Good job on your project. There are still a few fixes required.**

# Mandatory

1). **The navbar section is not displaying properly at 992px width.**

original | clone
--------- | -------
![newsweek_original](https://user-images.githubusercontent.com/38922385/93933384-4073b500-fd2a-11ea-92d4-10ca62b13e10.png) |  ![newsweek_clone](https://user-images.githubusercontent.com/38922385/93933413-4d90a400-fd2a-11ea-9bdc-3a193910ffc2.png)

2). **The circled section of the original webpage is missing on all screen sizes of your webpage. Please add it as it is part of the page and not an advert.**
(The screenshot below is for the full screen size.)

![sign_up_edited](https://user-images.githubusercontent.com/38922385/93934178-6cdc0100-fd2b-11ea-8217-6a851d26b36e.png)

# Optional

- For your readme section, you can display your github, twitter usernames instead of @githubhandle and @twitterhandle. Example, Github: @BigWizzo. 

## Good luck!😃.

**PS: You can reach me on slack (Rose Wanjohi)**

2020-09-22 23:32 UTC, umairarshadbutt commented
##
## Pull Request under review by Umair Arshad (TSE)

2020-09-22 23:42 UTC, umairarshadbutt requested changes
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @bigwizzo AND @410AngelaVU 
Good job with the changes! :tada: We are almost there.
We, however, do have some few changes to carry out before we proceed (see review comment).

##

 For this project, we have to make sure nothing is messed up. Kindly compare the screenshots below 👇 and work on the suggested changes.

- [x] Manage the flow of `My Turn`, `More stories`, `Top Stories`, `Feature Stories`, using the bootstrap classes. For better understanding, you can visit [newsweek](https://www.newsweek.com/)
### Subscribe
- [x] Add two more images
- [x] text should be overflow on images on small screens

|[Source Page](https://www.newsweek.com/)|[Clone Page](https://github.com/BigWizzo/newsweek-clone/tree/working-branch)|
|:---:|:---:|
|![source-page](https://user-images.githubusercontent.com/29689273/93947791-159f5600-fd56-11ea-9ad0-d9ce19060207.png)|![clone](https://user-images.githubusercontent.com/29689273/93947803-2354db80-fd56-11ea-9428-0b0f491f003b.png)|



##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you stick at any point or have any questions, let me know on slack at any time. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

2020-09-23 00:44 UTC, jubaan approved these changes
# Status: Approved :tada: :tada: :tada:

## Great job working on the previous required changes! 

There are no pending changes.

## :fireworks: You may now merge to master, Congrats!!! :clap: :clap: :clap:

2020-09-23 00:50 UTC, merged